config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount Sidekiq::Web => '/sidekiq'

  # resources :messages
  # resources :users_conversations
  # resources :notes
  # resources :conversations
  # resources :owner_images
  # resources :shared_images
  # resources :reviews
  # resources :comments
  # resources :food_informations
  resources :foods do
    collection do
      resource :import, controller: 'foods/imports', as: :food_import, only: %i[new create]
    end
  end
  resources :sources
  resources :users
  resources :categories
  # resources :categories_foods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top_pages#show'

  resources :search_by_keywords, as: :search_by_keywords, only: %i[index]
  resources :search_by_locations, as: :search_by_locations, only: %i[index]

  get :search, to: 'searchs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_food.rb
class CategoriesFood < ApplicationRecord
  belongs_to :category
  belongs_to :food
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  
  has_many :categories_foods
  has_many :foods, through: :categories_foods
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_one :note, dependent: :destroy
  has_many :users_conversations
  has_many :users, through: :users_conversations
end

app/models/food.rb
class Food < ApplicationRecord
  include FoodSearchable

  has_many :categories_foods
  has_many :categories, through: :categories_foods
  has_one :food_information, inverse_of: :food
  belongs_to :source
  belongs_to :user

  enum status: { pending: :pending, published: :published, unpublished: :unpublished }
end

app/models/food_information.rb
class FoodInformation < ApplicationRecord
  belongs_to :food, inverse_of: :food_information
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :conversation
end

app/models/owner_image.rb
class OwnerImage < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/shared_image.rb
class SharedImage < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  LOCATION = { latitude: '10.77307575675075', longitude: '106.72767170503232' }.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :shared_images
  has_many :owner_images
  has_many :messages, dependent: :destroy
  has_many :comments
  has_many :reviews
  has_many :foods
  has_many :users_conversations
  has_many :conversations, through: :users_conversations
end

app/controllers/foods/imports_controller.rb
class Foods::ImportsController < ApplicationController
  before_action :hierarchical_categories, only: [:new]

  def new; end
  
  def create
    ::Crawler::FoodyService.call(parameters)
    redirect_to new_food_import_path
  end

  private

    def hierarchical_categories
      @hierarchical_categories = Category.arrange(order: :display_name)
    end

    def parameters
      params.permit(:data_json, :source_id, :user_id, category: [])
    end
  
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :hierarchical_categories, only: [:new, :edit]

  # GET /foods
  # GET /foods.json
  def index
    @q = Food.ransack(params[:q])
    @foods = @q.result.includes(:categories).page(params[:page])
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:display_name, :status, :category_id, :source_id, :user_id)
    end

    def hierarchical_categories
      @hierarchical_categories = Category.arrange(order: :display_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def ancestry_options(items, text: :display_name)
    # items is hierarchical tree format.
    # { cate1, cate2: { cate3, cate4 } }
    result = []
    return result if items.blank?
    items.each do |item, sub_items|
      result << [('-' * item.depth) + item[text], item.id]
      result += ancestry_options(sub_items, text: text) if sub_items.present?
    end
    result
  end

  def categories_link_path(categories)
    safe_join(categories.map { |category| link_to(category.display_name, category_path(category.id)) }, ' / ')
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.slim
= simple_form_for @food do |f|
  - if @food.errors.any?
    #error_explanation
      h2 = "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      ul
        - @food.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.input :display_name, input_html: { class: 'form-control', placeholder: 'Ex: ...' }
  .form-group
    = f.input :category_ids, collection: ancestry_options(@hierarchical_categories), input_html: { class: 'form-control', multiple: true }
  .form-group = f.submit class: 'btn btn-primary'

app/views/foods/edit.html.slim
h1 Editing food

== render 'form'

=> link_to 'Show', @food
'|
=< link_to 'Back', foods_path

app/views/foods/index.html.slim
h1 Listing restaurants

br

= search_form_for @q do |f|
  .form-group
    = f.label :display_name_cont, 'Restaurent Name'
    = f.search_field :display_name_cont, class: 'form-control', placeholder: 'Ex: The LOG Restaurant'
  .form-group
    = f.label :source_display_name_cont, 'Source Name'
    = f.search_field :source_display_name_cont, class: 'form-control', placeholder: 'Ex: Foody'
  .form-group
    = f.label :categories_display_name_cont, 'Category Name'
    = f.search_field :categories_display_name_cont, class: 'form-control', placeholder: 'Ex: Sang trọng'
  .form-group
    = f.submit class: 'btn btn-default'

table.table
  thead
    tr
      th ID
      th Display name
      th Category
      th Source
      th User
      th
      th

  tbody
    - @foods.each do |food|
      tr
        td = food.id
        td = food.display_name
        td = food.categories.pluck(:display_name).join(', ')
        td = food.source.display_name
        td = food.user.name
        td = link_to 'Show', food
        td = link_to 'Edit', edit_food_path(food)

br

= paginate @foods

br

= link_to 'New Food', new_food_path
br
= link_to 'New Food By Importing', new_food_import_path

app/views/foods/new.html.slim
h1 New food

== render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.slim
p#notice = notice

table.table
  tbody
    tr
      th 
        strong
          | Display name:
      td = @food.display_name
    tr
      th 
        strong
          | Category:
      td = @food.categories.pluck(:display_name).join(', ')
    tr
      th 
        strong
          | Source:
      td = @food.source.display_name
    tr
      th 
        strong
          | User:
      td = @food.user.name
    tr
      th 
        strong
          | District:
      td = @food.food_information.district
    tr
      th 
        strong
          | City:
      td = @food.food_information.city
    tr
      th 
        strong
          | Total review:
      td = @food.food_information.total_review
    tr
      th 
        strong
          | Total view:
      td = @food.food_information.total_view
    tr
      th 
        strong
          | Average rating:
      td = @food.food_information.avg_rating
    tr
      th 
        strong
          | Review url:
      td
        - review_url = "https://www.foody.vn#{@food.food_information.review_url}"
        = link_to review_url, review_url, target: :blank
    tr
      th 
        strong
          | Album url:
      td
        - album_url = "https://www.foody.vn#{@food.food_information.album_url}"
        = link_to album_url, album_url, target: :blank
    tr
      th 
        strong
          | Latitude:
      td = @food.food_information.latitude
    tr
      th 
        strong
          | Longitude:
      td = @food.food_information.longitude
    tr
      th 
        strong
          | Location:
      td = @food.food_information.location
    tr
      th 
        strong
          | Detail url:
      td
        - detail_url = "https://www.foody.vn#{@food.food_information.detail_url}"
        = link_to detail_url, detail_url, target: :blank
    tr
      th 
        strong
          | Thumbnail:
      td = image_tag @food.food_information.thumbnail_url 

=> link_to 'Edit', edit_food_path(@food)
'|
=< link_to 'Back', foods_path